image: astait/copyclient_build_core:0.1.1

stages:
  - build

before_script:
  - cp $MAKEMK includes/make.mk
  - cp $CONFIGJS includes/config.js
  - mkdir -p $HOME/.ssh
  - cp $IDRSA $HOME/.ssh/id_rsa
  - cp $IDRSAPUB $HOME/.ssh/id_rsa.pub
  - cp $KNOWNHOSTS $HOME/.ssh/known_hosts
  - git submodule init
  - git submodule update --force
  - cp $MAKEMKNG src/make.mk
  - npm install

build-kiosk:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - make build-kiosk
  artifacts:
    paths:
    - dist/kiosk

build-directprint:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - make build-directprint
  artifacts:
    paths:
    - dist/directprint

build-win:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - make build-win
  artifacts:
    paths:
    - dist/public/windows

build-linux:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - make build-linux
  artifacts:
    paths:
    - dist/public/linux
