#!/bin/bash
################# "astaprint" CUPS backend script ##############################
#
# /usr/lib/cups/backend/astaprint
#
# (c) September 2007  Kurt Pfeifle <pfeifle@kde.org>
#                                  <kurt.pfeifle@infotec.com>
#     Network printing consultant Linux/Unix/Windows/Samba/CUPS
#
# Modifications by:
#     2018-2019       Michael Koch <mkoch@asta.upb.de>
#
# License: GNU GPLv2 or GPLv3 (your choice)
# Warranty: None at all; you may need to fix included defects on your own.

# helper variables
backend=${0}
jobid=${1}
cupsuser=${2}
jobtitle=${3}
jobcopies=${4}
joboptions=${5}
jobfile=${6}

# sanitize job title (only allow alphanumeric characters and a bit of punctuation)
# also remove .pdf from file name as it's added later on
sanitized_jobtitle="$(echo ${jobtitle} | tr -cd 'A-Za-zäöüÄÖÜß0-9 .()_-' | cut -c 1-80)"
sanitized_jobtitle="${sanitized_jobtitle%.pdf}"
outname=${sanitized_jobtitle}

case ${#} in
	0)
		# this case is for "backend discovery mode"
		echo "file astaprint \"AStA Copyclient Fakeprinter\" \"AStA Copyclient Fakeprinter for UNIX-like operating systems\""
		exit 0
		;;
	5)
		tmpfile="$(mktemp)"
		cat - > $tmpfile
		;;&
	6)
		tmpfile="$(mktemp)"
		cat ${6} > $tmpfile
		;;&
	5|6)
		if [ ! -e ${DEVICE_URI#astaprint:} ]; then
			mkdir -p ${DEVICE_URI#astaprint:}
			chmod 777 ${DEVICE_URI#astaprint:}
		fi

		outpdf=${DEVICE_URI#astaprint:}/${outname}.pdf

		# remove PJL shit
		if [[ $(head -n 3 $tmpfile) == *"@PJL"* ]]; then
			cat $tmpfile | sed -n '/^%PDF-/,$p' | sed -n '1,/^%%EOF/p' > "$outpdf"
		else
			mv $tmpfile "$outpdf"
		fi

		# remove tmp file
		rm $tmpfile

		# Make sure everyone can read and delete it
		chmod 777 "$outpdf"
		chown ${cupsuser} "$outpdf"

		# Open CC if not already opened, otherwise show window
		if [ -f "/opt/AStA Copyclient/asta-copyclient" ]; then
			nohup sudo -u ${cupsuser} DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/$(id -u ${cupsuser}) "/opt/AStA Copyclient/asta-copyclient" &>/dev/null &
		fi
		;;
	1|2|3|4|*)
		# these cases are unsupported
		echo " "
		echo " Usage: astaprint job-id user title copies options [file]"
		echo " "
		echo " (Install as CUPS backend in /usr/lib/cups/backend/astaprint)"
		echo " (Use as 'device URI' like \"astaprint:/path/to/writeable/directory\" for printer installation.)"
		exit 0
esac

# remove residual files older than 5 minutes
find "${DEVICE_URI#astaprint:}" -type f -mmin +5 -delete

echo 1>&2

################# end "astaprint" ##############################################
